# Generated by Django 4.2.1 on 2023-06-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('job_id', models.CharField(max_length=30, unique=True, verbose_name='工号')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=13, verbose_name='电话号码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='性别')),
                ('is_active', models.BooleanField(default=True, verbose_name='已激活')),
                ('user_type', models.CharField(choices=[('common', 'Common'), ('workflow_admin', 'Workflow Admin'), ('super_admin', 'Super Admin')], default='common', max_length=20, verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart_approver', to=settings.AUTH_USER_MODEL, verbose_name='部门审批人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_depart', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart_leader', to=settings.AUTH_USER_MODEL, verbose_name='部门领导')),
                ('parent_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_account.depart', verbose_name='父部门')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, verbose_name='岗位名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='岗位描述')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_jobtitle', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_userjob', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_include_user', to='app_account.jobtitle', verbose_name='岗位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perform_job', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_userdepart', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart_include_user', to='app_account.depart', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='belong_to_depart', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='worker',
            field=models.ManyToManyField(related_name='job_user', through='app_account.UserJob', to=settings.AUTH_USER_MODEL, verbose_name='用户岗位'),
        ),
        migrations.AddField(
            model_name='depart',
            name='worker',
            field=models.ManyToManyField(related_name='depart_user', through='app_account.UserDepart', to=settings.AUTH_USER_MODEL, verbose_name='用户部门'),
        ),
        migrations.AlterUniqueTogether(
            name='depart',
            unique_together={('name', 'parent_depart')},
        ),
    ]
