# Generated by Django 4.2.1 on 2023-06-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_remove_user_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
