# Generated by Django 4.2.1 on 2023-06-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=20, verbose_name='节点名称')),
                ('order_id', models.IntegerField(default=0, verbose_name='节点编号')),
                ('node_type', models.CharField(choices=[('begin', 'Begin'), ('serial', 'Serial'), ('parallel_all', 'Parallel All'), ('parallel_any', 'Parallel Any'), ('condition', 'Condition'), ('end', 'End')], default='begin', max_length=20, verbose_name='节点类型')),
                ('participant_type', models.CharField(blank=True, choices=[('one_person', 'One Person'), ('multi_person', 'Multi Person'), ('depart', 'Depart'), ('role', 'Role'), ('other', 'Other')], default='one_person', max_length=20, null=True, verbose_name='节点处理人类型')),
                ('participant_role', models.JSONField(default=dict, verbose_name='节点处理人-角色')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_node', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('participant_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_depart_participant', to='app_account.depart', verbose_name='节点处理人-部门')),
                ('participant_multi_person', models.ManyToManyField(related_name='node_multi_participant', to=settings.AUTH_USER_MODEL, verbose_name='节点处理人-多人')),
                ('participant_one_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_one_participant', to=settings.AUTH_USER_MODEL, verbose_name='节点处理人-单人')),
            ],
            options={
                'ordering': ['id', 'order_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工作流名称')),
                ('description', models.CharField(max_length=200, verbose_name='工作流描述')),
                ('able_to_cancel_approve', models.BooleanField(default=True, verbose_name='是否允许中途撤回审批')),
                ('able_to_add_countersign', models.BooleanField(default=True, verbose_name='是否允许中途加签')),
                ('able_to_transfer_approve', models.BooleanField(default=True, verbose_name='是否允许中途移交他人审批')),
                ('view_permission_check', models.BooleanField(default=True, verbose_name='是否限制工单的查看(仅限创建人、处理人查看工单)')),
                ('submit_ticket_check', models.BooleanField(default=False, verbose_name='是否限制工单的提交申请')),
                ('limit_expression', models.JSONField(default=dict, verbose_name='限制策略表达式')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_workflow', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, verbose_name='操作说明')),
                ('relation', models.CharField(choices=[('agree', 'Agree'), ('reject', 'Reject'), ('count_compare_condition_result', 'Condition Result 1'), ('right_or_wrong_condition_result', 'Condition Result 2')], max_length=50, verbose_name='转换关系类型')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_noderelation', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_node', to='app_workflow.node', verbose_name='目的节点')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_node', to='app_workflow.node', verbose_name='源节点')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_relation', to='app_workflow.workflow', verbose_name='所属工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node', to='app_workflow.workflow', verbose_name='所属工作流'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('field_name', models.CharField(max_length=50, verbose_name='自定义字段的名称')),
                ('description', models.CharField(max_length=200, verbose_name='自定义字段描述')),
                ('field_type', models.CharField(choices=[('count_compare', 'Count Compare'), ('right_or_wrong', 'Right Or Wrong')], max_length=20, verbose_name='自定义字段类型')),
                ('critical_value_list', models.JSONField(default=dict, verbose_name='数量比较字段_临界值列表')),
                ('compare_constant', models.JSONField(default=dict, verbose_name='事实对错比较字段_常量')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_customfield', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('field_in_node', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_field', to='app_workflow.node', verbose_name='关联的条件节点')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_custom_field', to='app_workflow.workflow', verbose_name='所属工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('low_bound', models.FloatField(blank=True, default=0, null=True, verbose_name='数量比较字段_下边界值')),
                ('low_bound_is_close', models.BooleanField(blank=True, default=False, null=True, verbose_name='下边界为闭区间')),
                ('up_bound', models.FloatField(blank=True, default=99999, null=True, verbose_name='数量比较字段_上边界值')),
                ('up_bound_is_close', models.BooleanField(blank=True, default=False, null=True, verbose_name='上边界为闭区间')),
                ('condition_is_satisfied', models.BooleanField(blank=True, null=True, verbose_name='事实成立的情况时')),
                ('condition_not_satisfied', models.BooleanField(blank=True, null=True, verbose_name='事实不成立的情况时')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_conditionresult', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('noderelation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='noderelation_conditionresult', to='app_workflow.noderelation', verbose_name='所属节点关系')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_conditionresult', to='app_workflow.workflow', verbose_name='所属工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('workflow', 'order_id')},
        ),
    ]
