# Generated by Django 4.2.1 on 2023-06-29 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_workflow', to=settings.AUTH_USER_MODEL, verbose_name='工作流创建人'),
        ),
        migrations.AlterUniqueTogether(
            name='noderelation',
            unique_together={('workflow', 'name')},
        ),
    ]
