# Generated by Django 4.2.1 on 2023-07-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workflow', '0003_alter_workflow_limit_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='view_permission_check',
        ),
    ]
