# Generated by Django 4.2.1 on 2023-06-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('title', models.CharField(max_length=100, verbose_name='工单标题')),
                ('sn', models.CharField(max_length=50, verbose_name='流水号')),
                ('is_adding_countersign', models.BooleanField(default=False, verbose_name='正在加签中')),
                ('add_countersign_person', models.JSONField(default=dict, verbose_name='加签人')),
                ('temporary_approver', models.JSONField(default=dict, verbose_name='被加签人')),
                ('state', models.CharField(choices=[('ongoing', 'Ongoing'), ('finish', 'Finish'), ('reject', 'Reject'), ('withdraw', 'Withdraw')], max_length=30, verbose_name='工单进行状态')),
                ('results_of_all_nodes', models.JSONField(default=dict, verbose_name='所有节点的处理结果')),
                ('data', models.JSONField(default=dict, verbose_name='表单原始内容')),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apply_ticket', to=settings.AUTH_USER_MODEL, verbose_name='工单申请人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_ticket', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('now_node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_now_node', to='app_workflow.node', verbose_name='当前所处节点')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workflow_ticket', to='app_workflow.workflow', verbose_name='所属工作流')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('suggestion', models.CharField(max_length=100, verbose_name='处理意见')),
                ('approveresult', models.CharField(choices=[('agree', 'Agree'), ('reject', 'Reject'), ('other', 'Other')], max_length=20, verbose_name='审批结果')),
                ('transactor', models.JSONField(default=dict, verbose_name='办理人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_ticketdetail', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail', to='app_ticket.ticket', verbose_name='所属工单')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
