# Generated by Django 4.2.1 on 2023-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='now_handler',
            field=models.JSONField(blank=True, default=dict, verbose_name='当前处理人的工号集合'),
        ),
    ]
