# Generated by Django 4.2.1 on 2023-06-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0002_ticket_now_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='now_handler',
            field=models.TextField(blank=True, null=True, verbose_name='当前处理人的工号集合'),
        ),
    ]
