# Generated by Django 4.2.1 on 2023-07-01 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ticket', '0006_alter_ticket_results_of_all_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdetail',
            name='creator',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='results_of_all_nodes',
            field=models.JSONField(default=list, verbose_name='所有节点的处理结果'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='transactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transact_ticket_detail', to=settings.AUTH_USER_MODEL, verbose_name='办理人'),
        ),
    ]
