# Generated by Django 4.2.1 on 2023-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0007_remove_ticketdetail_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='add_countersign_person',
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='is_temporary_countersign',
            field=models.BooleanField(default=False, verbose_name='是否属于临时加签'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='temporary_approver',
            field=models.TextField(blank=True, null=True, verbose_name='临时审批人'),
        ),
    ]
